#!/bin/sh

if test $# == 2; then

	awk	'
		BEGIN	{	
				FS=";";	
			}	
		(NR==1) {
				wkn=substr($0,8,6);
			}
		(NR>1)	{	
				 if (length($0)>10) {
					gsub(/,/,".",$4);
					gsub(/,/,".",$5);
					gsub(/,/,".",$6);
					gsub(/,/,".",$7);
					gsub(/,/,".",$8);
					gsub(/,/,".",$9);
				
					value=$4;	#tages-schlusskurs
					volume=$9;
					minimum=$8;
					maximum=$7;
					opening=$5;
					closing=$4;
				
					split($2,date,".");
				
					time=date[3]"-"date[2]"-"date[1]" 23:59:59";
					/*time=date[3]"-"date[2]"-"date[1]" "$3;*/
					printf "insert into %s (value,volume,minimum,maximum,opening,closing,time) values(%s,%s,%s,%s,%s,%s,\"%s\");\n",tname,value,volume,minimum,maximum,opening,closing,time;
				}
			}
		' tname=$2 $1
else
cat <<EOF
Usage:	swcsv2sql csvfile Tablename

EOF
fi
